# Importing the Libraries

In [40]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
import math

# Importing the Datasets

In [41]:
dataset_1 = pd.read_csv('train_1.csv')
dataset_2 = pd.read_csv('train_2.csv')

In [42]:
dataset_2.head()

timestamp               date_GMT    status  attendance     home_team_name  \
0  1533927600   Aug 10 2018 - 7:00pm  complete         NaN  Manchester United   
1  1533987000  Aug 11 2018 - 11:30am  complete         NaN   Newcastle United   
2  1533996000   Aug 11 2018 - 2:00pm  complete         NaN    AFC Bournemouth   
3  1533996000   Aug 11 2018 - 2:00pm  complete         NaN             Fulham   
4  1533996000   Aug 11 2018 - 2:00pm  complete         NaN  Huddersfield Town   

      away_team_name          referee  Pre-Match PPG (Home)  \
0     Leicester City   Andre Marriner                   0.0   
1  Tottenham Hotspur  Martin Atkinson                   0.0   
2       Cardiff City     Kevin Friend                   0.0   
3     Crystal Palace        Mike Dean                   0.0   
4            Chelsea   Chris Kavanagh                   0.0   

   Pre-Match PPG (Away)  home_ppg  ...  odds_ft_home_team_win  odds_ft_draw  \
0                   0.0      1.89  ...                   1.37          4.98   
1                   0.0      1.32  ...                   4.51          3.77   
2                   0.0      1.53  ...                   2.03          3.51   
3                   0.0      1.11  ...                   2.31          3.44   
4                   0.0      0.47  ...                   7.47          4.27   

   odds_ft_away_team_win  odds_ft_over15  odds_ft_over25  odds_ft_over35  \
0                   9.81            1.33            2.00            3.60   
1                   1.84            1.31            1.95            3.50   
2                   3.96            1.31            1.95            3.45   
3                   3.26            1.28            1.87            3.20   
4                   1.51            1.29            1.91            3.30   

   odds_ft_over45 odds_btts_yes odds_btts_no  \
0             0.0          2.05         1.69   
1             0.0          1.83         1.87   
2             0.0          1.83         1.83   
3             0.0          1.71         2.00   
4             0.0          2.00         1.71   

                                        stadium_name  
0                          Old Trafford (Manchester)  
1              St. James' Park (Newcastle upon Tyne)  
2             Vitality Stadium (Bournemouth- Dorset)  
3                            Craven Cottage (London)  
4  John Smith's Stadium (Huddersfield- West Yorks...  

[5 rows x 61 columns]

In [43]:
dataset_2.head()

timestamp               date_GMT    status  attendance     home_team_name  \
0  1533927600   Aug 10 2018 - 7:00pm  complete         NaN  Manchester United   
1  1533987000  Aug 11 2018 - 11:30am  complete         NaN   Newcastle United   
2  1533996000   Aug 11 2018 - 2:00pm  complete         NaN    AFC Bournemouth   
3  1533996000   Aug 11 2018 - 2:00pm  complete         NaN             Fulham   
4  1533996000   Aug 11 2018 - 2:00pm  complete         NaN  Huddersfield Town   

      away_team_name          referee  Pre-Match PPG (Home)  \
0     Leicester City   Andre Marriner                   0.0   
1  Tottenham Hotspur  Martin Atkinson                   0.0   
2       Cardiff City     Kevin Friend                   0.0   
3     Crystal Palace        Mike Dean                   0.0   
4            Chelsea   Chris Kavanagh                   0.0   

   Pre-Match PPG (Away)  home_ppg  ...  odds_ft_home_team_win  odds_ft_draw  \
0                   0.0      1.89  ...                   1.37          4.98   
1                   0.0      1.32  ...                   4.51          3.77   
2                   0.0      1.53  ...                   2.03          3.51   
3                   0.0      1.11  ...                   2.31          3.44   
4                   0.0      0.47  ...                   7.47          4.27   

   odds_ft_away_team_win  odds_ft_over15  odds_ft_over25  odds_ft_over35  \
0                   9.81            1.33            2.00            3.60   
1                   1.84            1.31            1.95            3.50   
2                   3.96            1.31            1.95            3.45   
3                   3.26            1.28            1.87            3.20   
4                   1.51            1.29            1.91            3.30   

   odds_ft_over45 odds_btts_yes odds_btts_no  \
0             0.0          2.05         1.69   
1             0.0          1.83         1.87   
2             0.0          1.83         1.83   
3             0.0          1.71         2.00   
4             0.0          2.00         1.71   

                                        stadium_name  
0                          Old Trafford (Manchester)  
1              St. James' Park (Newcastle upon Tyne)  
2             Vitality Stadium (Bournemouth- Dorset)  
3                            Craven Cottage (London)  
4  John Smith's Stadium (Huddersfield- West Yorks...  

[5 rows x 61 columns]

In [44]:
dataset_2_use = dataset_2[['home_team_name', 'away_team_name', 'home_team_goal_count', 'away_team_goal_count', 'average_goals_per_match_pre_match', 'btts_percentage_pre_match', 'over_15_percentage_pre_match', 'over_25_percentage_pre_match', 'over_35_percentage_pre_match', 'over_45_percentage_pre_match', 'over_15_HT_FHG_percentage_pre_match', 'over_05_HT_FHG_percentage_pre_match', 'average_corners_per_match_pre_match', 'average_cards_per_match_pre_match', 'odds_ft_home_team_win', 'odds_ft_draw', 'odds_ft_away_team_win', 'odds_ft_over15', 'odds_ft_over25', 'odds_ft_over35', 'odds_ft_over45', 'odds_btts_yes', 'odds_btts_no', 'total_goal_count']]

In [45]:
dataset_2_use.head()

home_team_name     away_team_name  home_team_goal_count  \
0  Manchester United     Leicester City                     2   
1   Newcastle United  Tottenham Hotspur                     1   
2    AFC Bournemouth       Cardiff City                     2   
3             Fulham     Crystal Palace                     0   
4  Huddersfield Town            Chelsea                     0   

   away_team_goal_count  average_goals_per_match_pre_match  \
0                     1                                0.0   
1                     2                                0.0   
2                     0                                0.0   
3                     2                                0.0   
4                     3                                0.0   

   btts_percentage_pre_match  over_15_percentage_pre_match  \
0                          0                             0   
1                          0                             0   
2                          0                             0   
3                          0                             0   
4                          0                             0   

   over_25_percentage_pre_match  over_35_percentage_pre_match  \
0                             0                             0   
1                             0                             0   
2                             0                             0   
3                             0                             0   
4                             0                             0   

   over_45_percentage_pre_match  ...  odds_ft_home_team_win  odds_ft_draw  \
0                             0  ...                   1.37          4.98   
1                             0  ...                   4.51          3.77   
2                             0  ...                   2.03          3.51   
3                             0  ...                   2.31          3.44   
4                             0  ...                   7.47          4.27   

   odds_ft_away_team_win  odds_ft_over15  odds_ft_over25  odds_ft_over35  \
0                   9.81            1.33            2.00            3.60   
1                   1.84            1.31            1.95            3.50   
2                   3.96            1.31            1.95            3.45   
3                   3.26            1.28            1.87            3.20   
4                   1.51            1.29            1.91            3.30   

   odds_ft_over45  odds_btts_yes  odds_btts_no  total_goal_count  
0             0.0           2.05          1.69                 3  
1             0.0           1.83          1.87                 3  
2             0.0           1.83          1.83                 2  
3             0.0           1.71          2.00                 2  
4             0.0           2.00          1.71                 3  

[5 rows x 24 columns]

In [46]:
dataset_2_use.describe()

home_team_goal_count  away_team_goal_count  \
count            380.000000            380.000000   
mean               1.568421              1.252632   
std                1.312836              1.180031   
min                0.000000              0.000000   
25%                1.000000              0.000000   
50%                1.000000              1.000000   
75%                2.000000              2.000000   
max                6.000000              6.000000   

       average_goals_per_match_pre_match  btts_percentage_pre_match  \
count                         380.000000                 380.000000   
mean                            2.681553                  50.350000   
std                             0.790425                  19.281859   
min                             0.000000                   0.000000   
25%                             2.460000                  44.750000   
50%                             2.785000                  52.000000   
75%                             3.050000                  59.000000   
max                             5.000000                 100.000000   

       over_15_percentage_pre_match  over_25_percentage_pre_match  \
count                    380.000000                    380.000000   
mean                      76.986842                     53.431579   
std                       21.528709                     19.770532   
min                        0.000000                      0.000000   
25%                       72.750000                     46.000000   
50%                       82.000000                     55.000000   
75%                       88.000000                     65.000000   
max                      100.000000                    100.000000   

       over_35_percentage_pre_match  over_45_percentage_pre_match  \
count                    380.000000                    380.000000   
mean                      29.947368                     13.078947   
std                       15.963757                     10.812827   
min                        0.000000                      0.000000   
25%                       22.000000                      5.000000   
50%                       30.000000                     13.000000   
75%                       39.000000                     19.000000   
max                      100.000000                     50.000000   

       over_15_HT_FHG_percentage_pre_match  \
count                           380.000000   
mean                             36.331579   
std                              17.372090   
min                               0.000000   
25%                              27.000000   
50%                              37.000000   
75%                              48.000000   
max                             100.000000   

       over_05_HT_FHG_percentage_pre_match  ...  odds_ft_home_team_win  \
count                           380.000000  ...             380.000000   
mean                             69.007895  ...               3.219421   
std                              20.733959  ...               2.962683   
min                               0.000000  ...               1.070000   
25%                              63.000000  ...               1.570000   
50%                              72.000000  ...               2.300000   
75%                              80.000000  ...               3.350000   
max                             100.000000  ...              22.000000   

       odds_ft_draw  odds_ft_away_team_win  odds_ft_over15  odds_ft_over25  \
count    380.000000             380.000000      380.000000      380.000000   
mean       4.471316               5.381816        1.257974        1.817684   
std        1.906924               5.540953        0.125338        0.325979   
min        2.900000               1.120000        0.000000        0.000000   
25%        3.350000               2.300000        1.180000        1.585000   
50%        3.750000               3.350000        1.250000        1.770000   
75%        4.8500

In [47]:
dataset = dataset_2_use.drop(labels=['home_team_goal_count', 'away_team_goal_count', 'home_team_name', 'away_team_name'], axis = 1)

In [48]:
dataset.head()

average_goals_per_match_pre_match  btts_percentage_pre_match  \
0                                0.0                          0   
1                                0.0                          0   
2                                0.0                          0   
3                                0.0                          0   
4                                0.0                          0   

   over_15_percentage_pre_match  over_25_percentage_pre_match  \
0                             0                             0   
1                             0                             0   
2                             0                             0   
3                             0                             0   
4                             0                             0   

   over_35_percentage_pre_match  over_45_percentage_pre_match  \
0                             0                             0   
1                             0                             0   
2                             0                             0   
3                             0                             0   
4                             0                             0   

   over_15_HT_FHG_percentage_pre_match  over_05_HT_FHG_percentage_pre_match  \
0                                    0                                    0   
1                                    0                                    0   
2                                    0                                    0   
3                                    0                                    0   
4                                    0                                    0   

   average_corners_per_match_pre_match  average_cards_per_match_pre_match  \
0                                  0.0                                0.0   
1                                  0.0                                0.0   
2                                  0.0                                0.0   
3                                  0.0                                0.0   
4                                  0.0                                0.0   

   odds_ft_home_team_win  odds_ft_draw  odds_ft_away_team_win  odds_ft_over15  \
0                   1.37          4.98                   9.81            1.33   
1                   4.51          3.77                   1.84            1.31   
2                   2.03          3.51                   3.96            1.31   
3                   2.31          3.44                   3.26            1.28   
4                   7.47          4.27                   1.51            1.29   

   odds_ft_over25  odds_ft_over35  odds_ft_over45  odds_btts_yes  \
0            2.00            3.60             0.0           2.05   
1            1.95            3.50             0.0           1.83   
2            1.95            3.45             0.0           1.83   
3            1.87            3.20             0.0           1.71   
4            1.91            3.30             0.0           2.00   

   odds_btts_no  total_goal_count  
0          1.69                 3  
1          1.87                 3  
2          1.83                 2  
3          2.00                 2  
4          1.71                 3

In [49]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

# Encoding categorical data

In [50]:
from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# le.fit(X[:, 0])
# X[:, 0] = le.transform(X[:, 0])
# X[:, 1] = le.transform(X[:, 1])

In [51]:
print(X)

[[ 0.  0.  0. ...  0.  2.  2.]
 [ 0.  0.  0. ...  0.  2.  2.]
 [ 0.  0.  0. ...  0.  2.  2.]
 ...
 [ 3. 59. 84. ...  0.  2.  2.]
 [ 3. 44. 64. ...  0.  2.  2.]
 [ 3. 50. 83. ...  0.  1.  3.]]


# Spliting into Train and Test Sets

In [52]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

# Feature Scaling

In [53]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# REGRESSION MODELS

# Decison Tree

In [54]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

In [55]:
y_pred = regressor.predict(X_test)
print(mean_squared_error(y_test, y_pred))
print(math.sqrt(mean_squared_error(y_test, y_pred)))

5.2368421052631575
2.2884147581378596


# Random Forest

In [56]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [57]:
y_pred = regressor.predict(X_test)
print(mean_squared_error(y_test, y_pred))
print(math.sqrt(mean_squared_error(y_test, y_pred)))

3.3228947368421053
1.8228808893732211


# Multiple Linear

In [58]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [59]:
y_pred = regressor.predict(X_test)
print(mean_squared_error(y_test, y_pred))
print(math.sqrt(mean_squared_error(y_test, y_pred)))

3.19889214495536
1.7885447002955672


In [60]:
np.set_printoptions(precision=0)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[3. 2.]
 [2. 2.]
 [3. 5.]
 [3. 4.]
 [3. 3.]
 [2. 3.]
 [3. 6.]
 [3. 5.]
 [3. 0.]
 [3. 7.]
 [3. 2.]
 [3. 1.]
 [3. 2.]
 [3. 3.]
 [2. 2.]
 [3. 5.]
 [3. 4.]
 [3. 4.]
 [2. 2.]
 [3. 1.]
 [3. 6.]
 [3. 4.]
 [3. 5.]
 [3. 1.]
 [2. 4.]
 [3. 2.]
 [3. 3.]
 [3. 5.]
 [3. 2.]
 [2. 3.]
 [3. 0.]
 [3. 3.]
 [3. 4.]
 [3. 0.]
 [4. 3.]
 [2. 2.]
 [3. 6.]
 [3. 4.]
 [3. 2.]
 [2. 2.]
 [3. 2.]
 [3. 3.]
 [1. 7.]
 [2. 3.]
 [2. 2.]
 [2. 4.]
 [3. 2.]
 [3. 3.]
 [3. 2.]
 [3. 4.]
 [3. 2.]
 [2. 3.]
 [2. 3.]
 [3. 4.]
 [3. 5.]
 [3. 2.]
 [3. 5.]
 [4. 7.]
 [3. 4.]
 [3. 3.]
 [3. 1.]
 [2. 1.]
 [2. 6.]
 [4. 3.]
 [3. 2.]
 [4. 5.]
 [2. 0.]
 [3. 5.]
 [3. 4.]
 [3. 2.]
 [3. 4.]
 [3. 1.]
 [3. 2.]
 [3. 2.]
 [3. 1.]
 [2. 1.]]


# Polynomial

In [61]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 6)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

LinearRegression()

In [62]:
y_pred = regressor.predict(poly_reg.transform(X_test))
print(mean_squared_error(y_test, y_pred))
print(math.sqrt(mean_squared_error(y_test, y_pred)))

82311.73236950189
286.90021326151344


# Support Vector

In [63]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

SVR()

In [64]:
y_pred = regressor.predict(X_test)
print(mean_squared_error(y_test, y_pred))
print(math.sqrt(mean_squared_error(y_test, y_pred)))

3.209681125233121
1.7915582952371718


# BUILDING ANN

In [65]:
import tensorflow as tf

In [66]:
ann = tf.keras.models.Sequential()

In [67]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [68]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [69]:
ann.add(tf.keras.layers.Dense(units=1))

# TRAINING THE ANN

In [70]:
ann.compile(optimizer='adam', loss='mean_squared_error')

In [71]:
ann.fit(X_train, y_train, batch_size=32, epochs=500)

Epoch 1/500
10/10 [==============================] - 0s 1ms/step - loss: 8.8765
Epoch 2/500
10/10 [==============================] - 0s 898us/step - loss: 8.4057
Epoch 3/500
10/10 [==============================] - 0s 1ms/step - loss: 7.9586
Epoch 4/500
10/10 [==============================] - 0s 1ms/step - loss: 7.5623
Epoch 5/500
10/10 [==============================] - 0s 1ms/step - loss: 7.1832
Epoch 6/500
10/10 [==============================] - 0s 1ms/step - loss: 6.8573
Epoch 7/500
10/10 [==============================] - 0s 2ms/step - loss: 6.5491
Epoch 8/500
10/10 [==============================] - 0s 1ms/step - loss: 6.2677
Epoch 9/500
10/10 [==============================] - 0s 1ms/step - loss: 6.0029
Epoch 10/500
10/10 [==============================] - 0s 1ms/step - loss: 5.7672
Epoch 11/500
10/10 [==============================] - 0s 898us/step - loss: 5.5378
Epoch 12/500
10/10 [==============================] - 0s 2ms/step - loss: 5.3254
Epoch 13/500
10/10 [=============

10/10 [==============================] - 0s 1ms/step - loss: 2.2888
Epoch 102/500
10/10 [==============================] - 0s 1ms/step - loss: 2.2888
Epoch 103/500
10/10 [==============================] - 0s 997us/step - loss: 2.2817
Epoch 104/500
10/10 [==============================] - 0s 1ms/step - loss: 2.2803
Epoch 105/500
10/10 [==============================] - 0s 1ms/step - loss: 2.2813
Epoch 106/500
10/10 [==============================] - 0s 1ms/step - loss: 2.2763
Epoch 107/500
10/10 [==============================] - 0s 1ms/step - loss: 2.2752
Epoch 108/500
10/10 [==============================] - 0s 1ms/step - loss: 2.2710
Epoch 109/500
10/10 [==============================] - 0s 2ms/step - loss: 2.2706
Epoch 110/500
10/10 [==============================] - 0s 1ms/step - loss: 2.2656
Epoch 111/500
10/10 [==============================] - 0s 1ms/step - loss: 2.2628
Epoch 112/500
10/10 [==============================] - 0s 997us/step - loss: 2.2626
Epoch 113/500
10/10 [=====

10/10 [==============================] - 0s 1ms/step - loss: 2.0466
Epoch 201/500
10/10 [==============================] - 0s 1ms/step - loss: 2.0465
Epoch 202/500
10/10 [==============================] - 0s 2ms/step - loss: 2.0438
Epoch 203/500
10/10 [==============================] - 0s 2ms/step - loss: 2.0441
Epoch 204/500
10/10 [==============================] - 0s 1ms/step - loss: 2.0398
Epoch 205/500
10/10 [==============================] - 0s 2ms/step - loss: 2.0388
Epoch 206/500
10/10 [==============================] - 0s 2ms/step - loss: 2.0384
Epoch 207/500
10/10 [==============================] - 0s 2ms/step - loss: 2.0365
Epoch 208/500
10/10 [==============================] - 0s 2ms/step - loss: 2.0359
Epoch 209/500
10/10 [==============================] - 0s 1ms/step - loss: 2.0372
Epoch 210/500
10/10 [==============================] - 0s 2ms/step - loss: 2.0325
Epoch 211/500
10/10 [==============================] - 0s 2ms/step - loss: 2.0310
Epoch 212/500
10/10 [=========

10/10 [==============================] - 0s 1ms/step - loss: 1.9352
Epoch 301/500
10/10 [==============================] - 0s 1ms/step - loss: 1.9363
Epoch 302/500
10/10 [==============================] - 0s 1ms/step - loss: 1.9322
Epoch 303/500
10/10 [==============================] - 0s 2ms/step - loss: 1.9346
Epoch 304/500
10/10 [==============================] - 0s 1ms/step - loss: 1.9303
Epoch 305/500
10/10 [==============================] - 0s 2ms/step - loss: 1.9318
Epoch 306/500
10/10 [==============================] - 0s 1ms/step - loss: 1.9277
Epoch 307/500
10/10 [==============================] - 0s 2ms/step - loss: 1.9306
Epoch 308/500
10/10 [==============================] - 0s 2ms/step - loss: 1.9286
Epoch 309/500
10/10 [==============================] - 0s 2ms/step - loss: 1.9290
Epoch 310/500
10/10 [==============================] - 0s 1ms/step - loss: 1.9279
Epoch 311/500
10/10 [==============================] - 0s 2ms/step - loss: 1.9252
Epoch 312/500
10/10 [=========

10/10 [==============================] - 0s 2ms/step - loss: 1.8572
Epoch 400/500
10/10 [==============================] - 0s 1ms/step - loss: 1.8578
Epoch 401/500
10/10 [==============================] - 0s 2ms/step - loss: 1.8524
Epoch 402/500
10/10 [==============================] - 0s 1ms/step - loss: 1.8520
Epoch 403/500
10/10 [==============================] - 0s 2ms/step - loss: 1.8533
Epoch 404/500
10/10 [==============================] - 0s 2ms/step - loss: 1.8555
Epoch 405/500
10/10 [==============================] - 0s 2ms/step - loss: 1.8509
Epoch 406/500
10/10 [==============================] - 0s 1ms/step - loss: 1.8482
Epoch 407/500
10/10 [==============================] - 0s 1ms/step - loss: 1.8469
Epoch 408/500
10/10 [==============================] - 0s 1ms/step - loss: 1.8443
Epoch 409/500
10/10 [==============================] - 0s 2ms/step - loss: 1.8439
Epoch 410/500
10/10 [==============================] - 0s 997us/step - loss: 1.8424
Epoch 411/500
10/10 [=======

Epoch 499/500
10/10 [==============================] - 0s 997us/step - loss: 1.7526
Epoch 500/500
10/10 [==============================] - 0s 1ms/step - loss: 1.7489


# Predicting the result of the test set

In [72]:
y_pred = ann.predict(X_test)

In [73]:
print(mean_squared_error(y_test, y_pred))
print(math.sqrt(mean_squared_error(y_test, y_pred)))

3.5434961333038157
1.8824176298855193
